# TypeProf 0.21.8

# Classes
module RPG
  class Troop
    class Member
      def initialize: -> void
      attr_accessor enemy_id: Integer
      attr_accessor x: Integer
      attr_accessor y: Integer
      attr_accessor hidden: bool
      attr_accessor immortal: bool
    end
  end
end


