# TypeProf 0.21.8

# Classes
module RPG
  class Troop
    class Page
      def initialize: -> void
      attr_accessor condition: Condition
      attr_accessor span: Integer
      attr_accessor list: Array[EventCommand]
    end
  end
end


