# TypeProf 0.21.8

# Classes
module RPG
  class Enemy
    class Action
      def initialize: -> void
      attr_accessor kind: Integer
      attr_accessor basic: Integer
      attr_accessor skill_id: Integer
      attr_accessor condition_turn_a: Integer
      attr_accessor condition_turn_b: Integer
      attr_accessor condition_hp: Integer
      attr_accessor condition_level: Integer
      attr_accessor condition_switch_id: Integer
      attr_accessor rating: Integer
    end
  end
end


