# TypeProf 0.21.8

# Classes
module RPG
  class Actor
    def initialize: -> void
    attr_accessor id: Integer
    attr_accessor name: String
    attr_accessor class_id: Integer
    attr_accessor initial_level: Integer
    attr_accessor final_level: Integer
    attr_accessor exp_basis: Integer
    attr_accessor exp_inflation: Integer
    attr_accessor character_name: String
    attr_accessor character_hue: Integer
    attr_accessor battler_name: String
    attr_accessor battler_hue: Integer
    attr_accessor parameters: Table
    attr_accessor weapon_id: Integer
    attr_accessor armor1_id: Integer
    attr_accessor armor2_id: Integer
    attr_accessor armor3_id: Integer
    attr_accessor armor4_id: Integer
    attr_accessor weapon_fix: bool
    attr_accessor armor1_fix: bool
    attr_accessor armor2_fix: bool
    attr_accessor armor3_fix: bool
    attr_accessor armor4_fix: bool
  end
end


