# TypeProf 0.21.8

# Classes
module RPG
  class Animation
    def initialize: -> void
    attr_accessor id: Integer
    attr_accessor name: String
    attr_accessor animation_name: String
    attr_accessor animation_hue: Integer
    attr_accessor position: Integer
    attr_accessor frame_max: Integer
    attr_accessor frames: Array[Frame]
    attr_accessor timings: Array[Timing]
  end
end



