# TypeProf 0.21.8

# Classes
module RPG
  class Armor
    def initialize: -> void
    attr_accessor id: Integer
    attr_accessor name: String
    attr_accessor icon_name: String
    attr_accessor description: String
    attr_accessor kind: Integer
    attr_accessor auto_state_id: Integer
    attr_accessor price: Integer
    attr_accessor pdef: Integer
    attr_accessor mdef: Integer
    attr_accessor eva: Integer
    attr_accessor str_plus: Integer
    attr_accessor dex_plus: Integer
    attr_accessor agi_plus: Integer
    attr_accessor int_plus: Integer
    attr_accessor guard_element_set: Array[Integer]
    attr_accessor guard_state_set: Array[Integer]
  end
end


