# TypeProf 0.21.8

# Classes
module RPG
  class AudioFile
    def initialize: (?String name, ?Integer volume, ?Integer pitch) -> void
    attr_accessor name: String
    attr_accessor volume: Integer
    attr_accessor pitch: Integer
  end
end



