# TypeProf 0.21.8

# Classes
module RPG
  module Cache
    self.@cache: Hash[String, Bitmap]

    def self.load_bitmap: (String folder_name, String filename, ?Integer hue) -> Bitmap
    def self.animation: (String filename, Integer hue) -> Bitmap
    def self.autotile: (String filename) -> Bitmap
    def self.battleback: (String filename) -> Bitmap
    def self.battler: (String filename, Integer hue) -> Bitmap
    def self.character: (String filename, Integer hue) -> Bitmap
    def self.fog: (String filename, Integer hue) -> Bitmap
    def self.gameover: (String filename) -> Bitmap
    def self.icon: (String filename) -> Bitmap
    def self.panorama: (String filename, Integer hue) -> Bitmap
    def self.picture: (String filename) -> Bitmap
    def self.tileset: (String filename) -> Bitmap
    def self.title: (String filename) -> Bitmap
    def self.windowskin: (String filename) -> Bitmap
    def self.tile: (String filename, Integer tile_id, Integer hue) -> Bitmap
    def self.clear: -> void
  end
end


