# TypeProf 0.21.8

# Classes
module RPG
  class Class
    def initialize: -> void
    attr_accessor id: Integer
    attr_accessor name: String
    attr_accessor position: Integer
    attr_accessor weapon_set: Array[Integer]
    attr_accessor armor_set: Array[Integer]
    attr_accessor element_ranks: Table
    attr_accessor state_ranks: Table
    attr_accessor learnings: Array[Integer]
  end
end



