# TypeProf 0.21.8

# Classes
module RPG
  class Enemy
    def initialize: -> void
    attr_accessor id: Integer
    attr_accessor name: String
    attr_accessor battler_name: String
    attr_accessor battler_hue: Integer
    attr_accessor maxhp: Integer
    attr_accessor maxsp: Integer
    attr_accessor str: Integer
    attr_accessor dex: Integer
    attr_accessor agi: Integer
    attr_accessor int: Integer
    attr_accessor atk: Integer
    attr_accessor pdef: Integer
    attr_accessor mdef: Integer
    attr_accessor eva: Integer
    attr_accessor animation1_id: Integer
    attr_accessor animation2_id: Integer
    attr_accessor element_ranks: Table
    attr_accessor state_ranks: Table
    attr_accessor actions: Array[Action]
    attr_accessor exp: Integer
    attr_accessor gold: Integer
    attr_accessor item_id: Integer
    attr_accessor weapon_id: Integer
    attr_accessor armor_id: Integer
    attr_accessor treasure_prob: Integer
  end
end



