# TypeProf 0.21.8

# Classes
module RPG
  class EventCommand
    def initialize: (?Integer code, ?Integer indent, ?Array[untyped] parameters) -> void
    attr_accessor code: Integer
    attr_accessor indent: Integer
    attr_accessor parameters: Array[untyped]
  end
end


