# TypeProf 0.21.8

# Classes
module RPG
  class Event
    def initialize: (Integer x, Integer y) -> void
    attr_accessor id: Integer
    attr_accessor name: String
    attr_accessor x: Integer
    attr_accessor y: Integer
    attr_accessor pages: Array[Page]
  end
end


