# TypeProf 0.21.8

# Classes
module RPG
  class Item
    def initialize: -> void
    attr_accessor id: Integer
    attr_accessor name: String
    attr_accessor icon_name: String
    attr_accessor description: String
    attr_accessor scope: Integer
    attr_accessor occasion: Integer
    attr_accessor animation1_id: Integer
    attr_accessor animation2_id: Integer
    attr_accessor menu_se: AudioFile
    attr_accessor common_event_id: Integer
    attr_accessor price: Integer
    attr_accessor consumable: bool
    attr_accessor parameter_type: Integer
    attr_accessor parameter_points: Integer
    attr_accessor recover_hp_rate: Integer
    attr_accessor recover_hp: Integer
    attr_accessor recover_sp_rate: Integer
    attr_accessor recover_sp: Integer
    attr_accessor hit: Integer
    attr_accessor pdef_f: Integer
    attr_accessor mdef_f: Integer
    attr_accessor variance: Integer
    attr_accessor element_set: Array[Integer]
    attr_accessor plus_state_set: Array[Integer]
    attr_accessor minus_state_set: Array[Integer]
  end
end


