# TypeProf 0.21.8

# Classes
module RPG
  class Map
    def initialize: (Integer width, Integer height) -> void
    attr_accessor tileset_id: Integer
    attr_accessor width: Integer
    attr_accessor height: Integer
    attr_accessor autoplay_bgm: bool
    attr_accessor bgm: AudioFile
    attr_accessor autoplay_bgs: bool
    attr_accessor bgs: AudioFile
    attr_accessor encounter_list: Array[Integer]
    attr_accessor encounter_step: Integer
    attr_accessor data: Table
    attr_accessor events: Hash[Integer, Event]
  end
end


