# TypeProf 0.21.8

# Classes
module RPG
  class MapInfo
    def initialize: -> void
    attr_accessor name: String
    attr_accessor parent_id: Integer
    attr_accessor order: Integer
    attr_accessor expanded: bool
    attr_accessor scroll_x: Integer
    attr_accessor scroll_y: Integer
  end
end



