# TypeProf 0.21.8

# Classes
module RPG
  class MoveRoute
    def initialize: -> void
    attr_accessor repeat: bool
    attr_accessor skippable: bool
    attr_accessor list: Array[MoveCommand]
  end
end



