# TypeProf 0.21.8

# Classes
module RPG
  class MoveCommand
    def initialize: (?Integer code, ?Array[untyped] parameters) -> void
    attr_accessor code: Integer
    attr_accessor parameters: Array[untyped]
  end
end


