# TypeProf 0.21.8

# Classes
module RPG
  class State
    def initialize: -> void
    attr_accessor id: Integer
    attr_accessor name: String
    attr_accessor animation_id: Integer
    attr_accessor restriction: Integer
    attr_accessor nonresistance: bool
    attr_accessor zero_hp: bool
    attr_accessor cant_get_exp: bool
    attr_accessor cant_evade: bool
    attr_accessor slip_damage: bool
    attr_accessor rating: Integer
    attr_accessor hit_rate: Integer
    attr_accessor maxhp_rate: Integer
    attr_accessor maxsp_rate: Integer
    attr_accessor str_rate: Integer
    attr_accessor dex_rate: Integer
    attr_accessor agi_rate: Integer
    attr_accessor int_rate: Integer
    attr_accessor atk_rate: Integer
    attr_accessor pdef_rate: Integer
    attr_accessor mdef_rate: Integer
    attr_accessor eva: Integer
    attr_accessor battle_only: bool
    attr_accessor hold_turn: Integer
    attr_accessor auto_release_prob: Integer
    attr_accessor shock_release_prob: Integer
    attr_accessor guard_element_set: Array[Integer]
    attr_accessor plus_state_set: Array[Integer]
    attr_accessor minus_state_set: Array[Integer]
  end
end


