# TypeProf 0.21.8

# Classes
module RPG
  class System
    def initialize: -> void
    attr_accessor magic_number: Integer
    attr_accessor party_members: Array[Integer]
    attr_accessor elements: Array[nil | String]
    attr_accessor switches: Array[nil | String]
    attr_accessor variables: Array[nil | String]
    attr_accessor windowskin_name: String
    attr_accessor title_name: String
    attr_accessor gameover_name: String
    attr_accessor battle_transition: String
    attr_accessor title_bgm: AudioFile
    attr_accessor battle_bgm: AudioFile
    attr_accessor battle_end_me: AudioFile
    attr_accessor gameover_me: AudioFile
    attr_accessor cursor_se: AudioFile
    attr_accessor decision_se: AudioFile
    attr_accessor cancel_se: AudioFile
    attr_accessor buzzer_se: AudioFile
    attr_accessor equip_se: AudioFile
    attr_accessor shop_se: AudioFile
    attr_accessor save_se: AudioFile
    attr_accessor load_se: AudioFile
    attr_accessor battle_start_se: AudioFile
    attr_accessor escape_se: AudioFile
    attr_accessor actor_collapse_se: AudioFile
    attr_accessor enemy_collapse_se: AudioFile
    attr_accessor words: Words
    attr_accessor test_battlers: Array[TestBattler]
    attr_accessor test_troop_id: Integer
    attr_accessor start_map_id: Integer
    attr_accessor start_x: Integer
    attr_accessor start_y: Integer
    attr_accessor battleback_name: String
    attr_accessor battler_name: String
    attr_accessor battler_hue: Integer
    attr_accessor edit_map_id: Integer
  end
end


