# TypeProf 0.21.8

# Classes
module RPG
  class Tileset
    def initialize: -> void
    attr_accessor id: Integer
    attr_accessor name: String
    attr_accessor tileset_name: String
    attr_accessor autotile_names: Array[String]
    attr_accessor panorama_name: String
    attr_accessor panorama_hue: Integer
    attr_accessor fog_name: String
    attr_accessor fog_hue: Numeric
    attr_accessor fog_opacity: Numeric
    attr_accessor fog_blend_type: Numeric
    attr_accessor fog_zoom: Numeric
    attr_accessor fog_sx: Numeric
    attr_accessor fog_sy: Numeric
    attr_accessor battleback_name: String
    attr_accessor passages: Table
    attr_accessor priorities: Table
    attr_accessor terrain_tags: Table
  end
end



