# TypeProf 0.21.8

# Classes
module RPG
  class Troop
    def initialize: -> void
    attr_accessor id: Integer
    attr_accessor name: String
    attr_accessor members: Array[Member]
    attr_accessor pages: [untyped]
  end
end



