class PokemonSnagListScene

  interface _SpriteHash

    def []: ("background" | "snagEntry") -> AnimatedPlane |
      ("snagList") -> WindowSnagList |
      ("icon" | "entryicon") -> PokemonSprite |
      ("overlay") -> BitmapSprite

    def []=: ("background" | "snagEntry", AnimatedPlane) -> void |
      ("snagList", WindowSnagList) -> void |
      ("icon" | "entryicon", PokemonSprite) -> void |
      ("overlay", BitmapSprite) -> void
  end

  class SpriteHash

    include ::_SpriteHash

    @background: Optional[AnimatedPlane]
    @snag_entry: Optional[AnimatedPlane]
    @snag_list: Optional[WindowSnagList]
    @icon: Optional[PokemonSprite]
    @entry_icon: Optional[PokemonSprite]
    @overlay: Optional[BitmapSprite]

    def initialize: -> void

    def background: -> AnimatedPlane

    def entry_icon: -> PokemonSprite

    def entry_icon=: (PokemonSprite value) -> void

    def icon: -> PokemonSprite

    def icon=: (PokemonSprite value) -> void

    def overlay: -> BitmapSprite

    def overlay=: (BitmapSprite value) -> void

    def snag_entry: -> AnimatedPlane

    def snag_list: -> WindowSnagList

    def snag_list=: (WindowSnagList value) -> void

    private

    def get_value: [T < Object] (String key, Optional[T] value) -> T

    def raise_type_mismatch_error: (String key, Class desired_type) -> void

  end

  @hw_bitmap: AnimatedBitmap
  @shape_bitmap: AnimatedBitmap
  @slider_bitmap: AnimatedBitmap
  @snag_order: Array[snag_entry]
  @sprites: SpriteHash
  @type_bitmap: AnimatedBitmap
  @viewport: Viewport

  def start_scene: () -> void

  def snag_entry: () -> void

  def end_scene: () -> void


  private

  def update: () -> void

  def set_icon_bitmap: (Symbol? species) -> void

  def get_snag_list: () -> Array[snag_entry]

  def refresh_snag_list: (?Integer index) -> void

  def refresh: () -> void

  def change_to_snag_entry: (Symbol species) -> void

  def snag_entry_on_index: (Integer index) -> void

  def parse_pokemon_location: (Symbol species) -> String

  def parse_evolution_line: (Symbol original, Pokemon? pkmn) -> bool

  def window_loop: (Integer current_index, Integer new_page, Integer page, Integer ret) -> void

  def cursor_down: (Integer current_index, Integer new_page, Integer page) -> [Integer, Integer]

  def cursor_up: (Integer current_index, Integer new_page, Integer page) -> [Integer, Integer]

  def on_window_cancel: (Integer page) -> void
end



