class ShadowPokemonDataTest < Minitest::Test
  def test_register_snag_and_purify: -> void

  def test_shadow_and_snag_order: -> void

  def test_snag_index: -> void

  private

  def convert_ivs: (Array[Integer] ivs)-> Hash[Symbol, Integer]
end
