# TypeProf 0.21.8

# Classes
module RPG
  class System
    class TestBattler
      def initialize: -> void
      attr_accessor actor_id: Integer
      attr_accessor level: Integer
      attr_accessor weapon_id: Integer
      attr_accessor armor1_id: Integer
      attr_accessor armor2_id: Integer
      attr_accessor armor3_id: Integer
      attr_accessor armor4_id: Integer
    end
  end
end


