# TypeProf 0.21.8

# Classes
module RPG
  class System
    class Words
      def initialize: -> void
      attr_accessor gold: String
      attr_accessor hp: String
      attr_accessor sp: String
      attr_accessor str: String
      attr_accessor dex: String
      attr_accessor agi: String
      attr_accessor int: String
      attr_accessor atk: String
      attr_accessor pdef: String
      attr_accessor mdef: String
      attr_accessor weapon: String
      attr_accessor armor1: String
      attr_accessor armor2: String
      attr_accessor armor3: String
      attr_accessor armor4: String
      attr_accessor attack: String
      attr_accessor skill: String
      attr_accessor guard: String
      attr_accessor item: String
      attr_accessor equip: String
    end
  end
end


