# TypeProf 0.21.8

# Classes
module RPG
  class Animation
    class Timing
      def initialize: -> void
      attr_accessor frame: Integer
      attr_accessor se: AudioFile
      attr_accessor flash_scope: Integer
      attr_accessor flash_color: Color
      attr_accessor flash_duration: Integer
      attr_accessor condition: Integer
    end
  end
end



