# TypeProf 0.21.8

# Classes
module RPG
  class Troop
    class Page
      class Condition
        def initialize: -> void
        attr_accessor turn_valid: bool
        attr_accessor enemy_valid: bool
        attr_accessor actor_valid: bool
        attr_accessor switch_valid: bool
        attr_accessor turn_a: Integer
        attr_accessor turn_b: Integer
        attr_accessor enemy_index: Integer
        attr_accessor enemy_hp: Integer
        attr_accessor actor_id: Integer
        attr_accessor actor_hp: Integer
        attr_accessor switch_id: Integer
      end
    end
  end
end



