# TypeProf 0.21.8

# Classes
module RPG
  class Event
    class Page
      def initialize: -> void
      attr_accessor condition: Condition
      attr_accessor graphic: Graphic
      attr_accessor move_type: Integer
      attr_accessor move_speed: Integer
      attr_accessor move_frequency: Integer
      attr_accessor move_route: MoveRoute
      attr_accessor walk_anime: bool
      attr_accessor step_anime: bool
      attr_accessor direction_fix: bool
      attr_accessor through: bool
      attr_accessor always_on_top: bool
      attr_accessor trigger: Integer
      attr_accessor list: Array[EventCommand]
    end
  end
end



