# TypeProf 0.21.8

# Classes
class Bitmap
  include _CheckedDisposable
  include _Drawable

  def self.max_size: -> Rect


  def initialize: (Integer width, Integer height) -> void
                | (String filename) -> void
  def rect: -> Rect
  def blt: (Integer x, Integer y, Bitmap src_bitmap, Rect src_rect, ?Integer opacity) -> void
  def stretch_blt: (Rect dest_rect, Bitmap src_bitmap, Rect src_rect, ?Integer opacity) -> void
  def fill_rect: (Integer x, Integer y, Integer width, Integer height, Color color) -> void
               | (Rect rect, Color color) -> void
  def gradient_fill_rect: (Integer x, Integer y, Integer width, Integer height, Color color) -> void
                        | (Rect rect, Color color) -> void
  def clear: -> void
  def clear_rect: (Integer x, Integer y, Integer width, Integer height) -> void
                | (Rect rect) -> void
  def get_pixel: (Integer x, Integer y) -> Color
  def set_pixel: (Integer x, Integer y, Color color) -> void
  def hue_change: (Integer hue) -> void
  def blur: -> void
  def radial_blur: (Integer angle, Integer division) -> void
  def draw_text: (Integer x, Integer y, Integer width, Integer height, String str, ?Integer align) -> void
               | (Rect rect, String str, ?Integer align) -> void
  def text_size: (String str) -> Rect
  def mega?: -> bool
  def to_file: (String path) -> void

  def animated?: -> bool
  def current_frame: -> Integer
  def frame_count: -> Integer
  def play: -> void
  def stop: -> void
  def goto_and_play: (Integer pos) -> void
  def goto_and_stop: (Integer pos) -> void
  def next_frame: -> void
  def previous_frame: -> void
  def add_frame: (Bitmap source, ?Integer position) -> void
  def remove_frame: (?Integer position) -> void
  def snap_to_bitmap: (?Integer position) -> void

  attr_accessor font: Font
  attr_accessor raw_data: String
  attr_accessor playing: bool
  attr_accessor looping: bool
  attr_accessor frame_rate: Integer
end



