# TypeProf 0.21.8

# Classes
class Color
  def set: (_Number red, ?_Number green, ?_Number blue, ?_Number alpha) -> void
         | (Color color) -> void

  attr_accessor red: _Number
  attr_accessor green: _Number
  attr_accessor blue: _Number
  attr_accessor alpha: _Number
end



