# TypeProf 0.21.8

# Classes
class Color
  def set: (number red, ?number green, ?number blue, ?number alpha) -> void
         | (Color color) -> void

  attr_accessor red: number
  attr_accessor green: number
  attr_accessor blue: number
  attr_accessor alpha: number
end



