# TypeProf 0.21.8

# Classes
class Color
  def set: (Math::double red, ?Math::double green, ?Math::double blue, ?Math::double alpha) -> void
         | (Color color) -> void

  attr_accessor red: Math::double
  attr_accessor green: Math::double
  attr_accessor blue: Math::double
  attr_accessor alpha: Math::double
end



