# TypeProf 0.21.8

# Classes
class Font
  def initialize: (?String name, ?Input size) -> void
  def self.exist?: (String name) -> bool
  def self.default_name: -> String
  def self.default_size: -> Integer
  def self.default_bold: -> bool
  def self.default_italic: -> bool
  def self.default_outline: -> bool
  def self.default_shadow: -> bool
  def self.default_color: -> Color
  def self.default_out_color: -> Color

  attr_accessor name: String
  attr_accessor size: Integer
  attr_accessor bold: bool
  attr_accessor italic: bool
  attr_accessor outline: bool
  attr_accessor shadow: bool
  attr_accessor color: Color
  attr_accessor out_color: Color

end


