# TypeProf 0.21.8

# Classes
class Object
  private
  def rgss_main: -> void
  def rgss_stop: -> void
  def load_data: (String filename, ?bool restore) -> untyped
  def save_data: (untyped obj, String filename) -> void
  def msgbox: (*String args) -> void
  def msgbox_p: (*untyped objs) -> void
end


