# TypeProf 0.21.8

type button_enum = :LEFT | :UP | :RIGHT | :DOWN | :A | :B | :X | :Y | :L | :R | :SHIFT | :CTRL |
  :ALT | :F5 | :F6 | :F7 | :F8 | :F9

# Classes
module Input
  LEFT: button_enum
  UP: button_enum
  RIGHT: button_enum
  DOWN: button_enum
  A: button_enum
  B: button_enum
  C: button_enum
  X: button_enum
  Y: button_enum
  Z: button_enum
  L: button_enum
  R: button_enum
  SHIFT: button_enum
  CTRL: button_enum
  ALT: button_enum
  F5: button_enum
  F6: button_enum
  F7: button_enum
  F8: button_enum
  F9: button_enum

  def self?.update: -> void
  def self?.press?: (button_enum sym) -> bool
  def self?.trigger?: (button_enum sym) -> bool
  def self?.repeat?: (button_enum sym) -> bool
  def self?.release?: (button_enum sym) -> bool
  def self?.pressex?: (Symbol | Integer sym) -> bool
  def self?.triggerex?: (Symbol | Integer sym) -> bool
  def self?.repeatex?: (Symbol | Integer sym) -> bool
  def self?.releaseex?: (Symbol | Integer sym) -> bool
  def self?.dir4: -> Integer
  def self?.dir8: -> Integer

  def gets: -> String
  def raw_key_state: -> bool
  def scroll_v: -> Integer
  def mouse_x: -> Integer
  def mouse_y: -> Integer
  def mouse_in_window?: -> bool

  attr_accessor text_input: bool
  attr_accessor clipboard: String
  attr_accessor show_cursor: bool

  module Controller

    def connected?: -> bool
    def name: -> String
    def pressex?: (Symbol | Integer sym) -> bool
    def triggerex?: (Symbol | Integer sym) -> bool
    def repeatex?: (Symbol | Integer sym) -> bool
    def releaseex?: (Symbol | Integer sym) -> bool
    def power_level: -> Symbol
    def axes_left: -> Float
    def axes_right: -> Float
    def axes_trigger: -> Array[Float]
    def raw_button_states: -> Array[bool]
    def raw_axes: -> Array[Float]

  end

end


