# TypeProf 0.21.8

# Classes
class Plane
  include _Visualizable

  def initialize: (?Viewport? viewport) -> void
  def dispose: -> void
  def disposed?: -> bool

  attr_accessor bitmap: Bitmap?
  attr_accessor viewport: Viewport
  attr_accessor visible: bool
  attr_accessor z: Integer
  attr_accessor ox: Integer
  attr_accessor oy: Integer
  attr_accessor zoom_x: Float
  attr_accessor zoom_y: Float
  attr_accessor opacity: Integer
  attr_accessor blend_type: Integer
  attr_accessor color: Color
  attr_accessor tone: Tone
end



