# TypeProf 0.21.8

# Classes
class Plane
  include _Visualizable
  include _CheckedDisposable

  def initialize: (?Viewport? viewport) -> void

  @visible: bool

  attr_accessor bitmap: Bitmap?
  attr_accessor viewport: Viewport
  attr_accessor z: Integer
  attr_accessor ox: Integer
  attr_accessor oy: Integer
  attr_accessor zoom_x: Float
  attr_accessor zoom_y: Float
  attr_accessor opacity: Integer
  attr_accessor blend_type: Integer
  attr_accessor color: Color
  attr_accessor tone: Tone
end



