# TypeProf 0.21.8

# Classes
class Rect
  def initialize: (Integer x, Integer y, Integer width, Integer height) -> void
                | () -> void
  def set: (Integer x, Integer y, Integer width, Integer height) -> void
         | (Rect rect) -> void
  def empty: -> bool

  attr_accessor x: Integer
  attr_accessor y: Integer
  attr_accessor width: Integer
  attr_accessor height: Integer
end



