# TypeProf 0.21.8

# Classes
class Sprite
  include _CheckedDisposable
  include _Updatable
  include _Visualizable

  def initialize: (?Viewport? viewport) -> void
  def flash: (Color color, Integer duration) -> void
  def width: -> Integer
  def height: -> Integer

  @visible: bool

  attr_accessor bitmap: Bitmap?
  attr_accessor src_rect: Rect
  attr_accessor viewport: Viewport
  attr_accessor x: Integer
  attr_accessor y: Integer
  attr_accessor z: Integer
  attr_accessor ox: Integer
  attr_accessor oy: Integer
  attr_accessor zoom_x: Math::double
  attr_accessor zoom_y: Math::double
  attr_accessor angle: Integer
  attr_accessor wave_amp: Math::double
  attr_accessor wave_length: Math::double
  attr_accessor wave_speed: Math::double
  attr_accessor wave_phase: Math::double
  attr_accessor mirror: bool
  attr_accessor bush_depth: Integer
  attr_accessor bush_opacity: Integer
  attr_accessor opacity: Math::double
  attr_accessor blend_type: Integer
  attr_accessor color: Color
  attr_accessor tone: Tone

  attr_accessor pattern: Bitmap
  attr_accessor pattern_blend_type: Integer
  attr_accessor pattern_tile: bool
  attr_accessor pattern_scroll_x: Integer
  attr_accessor pattern_scroll_y: Integer
  attr_accessor pattern_opacity: Integer
  attr_accessor pattern_zoom_x: Float
  attr_accessor pattern_zoom_y: Float
  attr_accessor invert: bool
end



