# TypeProf 0.21.8

type power_state = {
    :discharging => bool,
    :percent => Integer,
    :seconds => Integer
  }

# Classes
module System
  VERSION: String

  attr_accessor window_tile: String

  def self?.data_directory: -> String
  def self?.lauch: (String cmd, Array[String] args) -> void
  def self?.user_language: -> String
  def self?.game_title: -> String
  def self?.show_settings: -> void
  def self?.power_state: -> power_state
  def self?.uptime: -> number
  def self?.platform: -> String
  def self?.is_windows?: -> bool
  def self?.is_mac?: -> bool
  def self?.is_linux?: -> bool
  def self?.is_rosetta?: -> bool
  def self?.is_wine?: -> bool
  def self?.is_really_windows?: -> bool
  def self?.is_really_mac?: -> bool
  def self?.is_really_linux?: -> bool
  def self?.desensitize: (String path) -> void
  def self?.reload_cache: -> void
  def self?.unmount: (String path, ?bool reload) -> void
  def self.user_name: -> String

  def self?.set_window_title: (String) -> void
end



