# TypeProf 0.21.8

# Classes
class Table
  def initialize: (Integer xsize, ?Integer ysize, ?Integer zsize) -> void
  def resize: (Integer xsize, ?Integer ysize, ?Integer zsize) -> void
  def xsize: -> Integer
  def ysize: -> Integer
  def zsize: -> Integer
  def []: (Integer x, ?Integer y, ?Integer z) -> Integer
  def []=: (Integer x, ?Integer y, ?Integer z, ?Integer value) -> Integer
end


