# TypeProf 0.21.8

# Classes
class Tilemap
  include _CheckedDisposable
  include _Updatable
  include _Visualizable

  def initialize: (?Viewport viewport) -> void

  attr_accessor viewport: Viewport
  attr_accessor tileset: Bitmap
  attr_accessor  autotiles: Array[Bitmap]
  attr_accessor map_data: Table
  attr_accessor flash_data: Table
  attr_accessor priorities: Table
  @visible: bool
  attr_accessor ox: Integer
  attr_accessor oy: Integer
end



