# TypeProf 0.21.8

# Classes
class Tone
  def initialize: (Math::double red, Math::double green, Math::double blue, Math::double gray) -> void
                | () -> void
  def set: (Math::double red, Math::double green, Math::double blue, Math::double gray) -> void
         | (Tone tone) -> void

  attr_accessor red: Math::double
  attr_accessor green: Math::double
  attr_accessor blue: Math::double
  attr_accessor gray: Math::double
end



