# TypeProf 0.21.8

# Classes
class Tone
  def initialize: (number red, number green, number blue, number gray) -> void
                | () -> void
  def set: (number red, number green, number blue, number gray) -> void
         | (Tone tone) -> void

  attr_accessor red: number
  attr_accessor green: number
  attr_accessor blue: number
  attr_accessor gray: number
end



