# TypeProf 0.21.8

# Classes
class Tone
  def initialize: (Numeric red, Numeric green, Numeric blue, Numeric gray) -> void
                | () -> void
  def set: (Numeric red, Numeric green, Numeric blue, Numeric gray) -> void
         | (Tone tone) -> void

  attr_accessor red: Numeric
  attr_accessor green: Numeric
  attr_accessor blue: Numeric
  attr_accessor gray: Numeric
end



