# TypeProf 0.21.8

# Classes
class Viewport
  include _CheckedDisposable
  include _Updatable
  include _Visualizable

  def initialize: (Integer x, Integer y, Integer width, Integer height) -> void
                | (Rect rect) -> void
                | () -> void
  def flash: (Color color, Integer duration) -> void

  attr_accessor rect: Rect
  attr_accessor visible: bool
  attr_accessor z: Integer
  attr_accessor ox: Integer
  attr_accessor oy: Integer
  attr_accessor color: Color
  attr_accessor tone: Tone
end


