# TypeProf 0.21.8

# Classes
class Window
  include _CheckedDisposable
  include _Updatable
  include _Visualizable

  def initialize: (Viewport? viewport) -> void |
    () -> void

  @visible: bool

  def windowskin: %a{implicitly-returns-nil} () -> Bitmap
  def windowskin=: (Bitmap? value) -> void

  def contents: %a{implicitly-returns-nil} () -> Bitmap
  def contents=: (Bitmap? value) -> void

  attr_accessor stretch: bool
  attr_accessor cursor_rect: Rect
  attr_accessor viewport: Viewport?
  attr_accessor active: bool
  attr_accessor pause: bool
  attr_accessor x: Integer
  attr_accessor y: Integer
  attr_accessor width: Integer
  attr_accessor height: Integer
  attr_accessor z: Integer
  attr_accessor ox: Integer
  attr_accessor oy: Integer
  attr_accessor opacity: Numeric
  attr_accessor back_opacity: Numeric
  attr_accessor contents_opacity: Numeric
end



