name: Test and Scan Plugins
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: ghcr.io/fcorso2016/mkxp-z:0f4373e4b1c1a8fc044a59fd4e78d5d669e261ca
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: bundle install

      - name: Run Tests
        run: rake

      - uses: actions/upload-artifact@v3
        with:
          name: plugins.tests.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: coverage/

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    container: sonarsource/sonar-scanner-cli
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - uses: actions/download-artifact@v3
        with:
          name: plugins.tests.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: coverage/

      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner --define sonar.host.url=https://sonarcloud.io --define sonar.projectKey=fcorso2016_pokemon-essentials-plugins --define sonar.sources=Plugins,game_core.rb,game.rb --define sonar.tests=Tests --define sonar.ruby.coverage.reportPaths=coverage/coverage.json